const jsonOne = {
    "LangID": "1",
    "ServiceId": "1253",
    "ServiceName": "Age Domicile Certificate",
    "UserID": "224a14e9-33e8-4c5a-8d48-fe20d26769f6",
    "DivisionId": "6",
    "CertificateType": "Certificate of Age and Domicile",
    "CertificateTypeCode": "AD",
    "ApplicantSalutation": "09C5B7FA-97B9-4044-9F48-BF1B0B61FB0B",
    "ApplicantNameEnglish": "MAHESH DHANAVADE",
    "ApplicantNameMarathi": "Jayesh",//required
    "ApplicantFatherSalutation": "F844A285-2EA3-402B-BBEB-29E49606380B",
    "ApplicantFatherNameEnglish": "Father name basic screen ",
    "ApplicantFatherNameMarathi": "Father name basic screen marathi",
    "ApplicantDOB": "1953-01-10",
    "ApplicantAge": "71",
    "ApplicantMobileNo": "9999999999",
    "ApplicantGender": "F",
    "ApplicantEmailID": "jayeshnandurkar3@gmail.com",
    "ApplicantOccupation": "899BA63A-842C-4750-AA7B-907DB4554B7B",
    "ApplicantNationality": "INDIAN",
    "ResidingAtPresentAddressSince": "2023",
    "ApplicantAddress": "Basic screen applicant address ",
    "ApplicantBuilding": "Building basic screen ",
    "ApplicantSection": "Basic screen section ",
    "ApplicantStreet": "Basic screen applicant address ",
    "ApplicantLandmark": "Basic screen landmark ",
    "ApplicantStateCode": "27",
    "ApplicantDistrictCode": "506",
    "ApplicantSubDistrictCode": "4040",
    "ApplicantVillageCode": "537082",
    "ApplicantPinCode": "996633",
    "BeneficiaryResidingCurrentAddress": "2023",
    "ApplicantResidingMaharashtra": "24",
    "ApplicantRelationWithBeneficiary": "A2DB24FD-3560-4138-9F34-DE7647A42EAE",
    "BeneficiarySalutation": "09C5B7FA-97B9-4044-9F48-BF1B0B61FB0B",
    "BeneficiaryName": "Beneficiary Full name ",
    "BeneficiaryDOB": "2006-05-22",
    "BeneficiaryMobile": "9966336699",
    "PresentAddressSameAsAbove": "नाही",
    "PresentAddress": "Present address ",
    "PresentBuilding": "Building ",
    "PresentSection": "Section ",
    "PresentStreet": "Street ",
    "PresentLandmark": "Landmark ",
    "PresentDistrictCode": "530",
    "PresentSubDistrictCode": "4284",
    "PresentVillageCode": "567189",
    "PresentPinCode": "336699",
    "BirthAddressSameAsAbove": "नाही",
    "BirthAddress": "Birth address ",
    "BirthBuilding": "",
    "BirthSection": "",
    "BirthStreet": "",
    "BirthStateCode": "27",
    "BirthDistrictCode": "530",
    "BirthSubDistrictCode": "4292",
    "BirthVillageCode": "567916",
    "BirthPinCode": "996633",
    "ListEducationDetailsofBeneficiaryModel": [
        {
            "EducationDetailsofBeneficiary": "2BB4D79C-ECBE-4B3C-BFD1-4AC24764AA7E",
            "University": "",
            "AdmissionYear": "",
            "CompletionYear": "",
            "InstituteDetails": ""
        }
    ],
    "IsBeneficiaryaMarriedWoman": "24D0812D-9882-4A3E-80E8-E2B3971BA308",
    "MaidenName": "",
    "MarriageDate": "2011-05-22",
    "AddressBeforeMarriageSameasSbove": "Address after married women ",
    "BeforeMarriageAddress": "Address for married women ",
    "BeforeMarriageBuilding": "",
    "BeforeMarriageSection": "",
    "BeforeMarriageStreet": "",
    "BeforeMarriageLandmark": "",
    "BeforeMarriageDistrictCode": "530",
    "BeforeMarriageSubDistrictCode": "4293",
    "BeforeMarriageVillageCode": "567991",
    "BeforeMarriagePinCode": "996633",
    "PlacewhereMarriageWasRegistered": "",
    "PostMarriageNameAlongWithHusbandName": "",
    "ResidingPeriodBeforMarriageAndNoofYear": "2000-05-22",
    "PlaceofBirthofHusband": "",
    "DateofBirthofHusband": "1992-05-22",
    "OccupationofHusband": "23DACB05-EA28-45F1-94DF-16CA2CA6894A",
    "HusbandName": "",
    "AddressAfterMarriageSameasAbove": "नाही",
    "AfterMarriageAddress": "",
    "AfterMarriageBuilding": "",
    "AfterMarriageSection": "",
    "AfterMarriageStreet": "",
    "AfterMarriageLandmark": "",
    "AfterMarriageDistrictCode": "530",
    "AfterMarriageSubDistrictCode": "4290",
    "AfterMarriageVillageCode": "",
    "AfterMarriagePinCode": "868833",
    "HasBeneficiaryMigratedFromDifferentState": "E5B855ED-DE8A-497A-B055-98666BC365CA",
    "YearsOfResidenceInMaharashtra": "1977",
    "FamilyNativePlaceBeforeMigrationToMaharashtra": "Native Place ",//required
    "ReasonforMigration": "Reason for migration",//required
    "ListMigrationDetailsofBeneficiaryModel": [
        {
            "MigrationPlace": "Migration place \n From Year",
            "FromYear": "",
            "ToYear": ""
        }
    ],
    "DetailsOfMovablePropertyBelongToApplicantFatherhusbandInMaharashtra": "नाही",
    "PropertyAddress": "",
    "PropertyBuilding": "",
    "PropertySection": "",
    "PropertyStreet": "",
    "PropertyLandmark": "",
    "PropertyDistrictCode": "",
    "PropertySubDistrictCode": "",
    "PropertyVillageCode": "",
    "PropertyPinCode": "",
    "PropertyHolderRelationwithBeneficiary": "aa6f3900-f4f0-43df-92ba-2433093a2f42",
    "PropertyDetail": "",
    "Beneficiaryfatherhusbandplaceofresidence": "",
    "Atthetimeofbirthofthebeneficiaryplaceofresidenceoffather": "",
    "IfBeneficiaryfatherhusbandisstayingoutsideMaharashtrathenplaceofresidence": "",
    "Placeofemploymentenrolmentforschemeifany": "",
    "WhetherApplicantIsBeneficiaryOfGovernmentSchemeinOtherDistrict": "हो",
    "PolicyDistrictCode": "508",
    "PolicySubDistrictCode": "4054",
    "PolicyVillageCode": "aa6f3",
    "PolicyPinCode": "",
    "ListApplicantFamilyResidantDetailsModel": [
        {
            "RelationWithBeneficiary": "CFD7FC5B-0108-4660-8994-593D2D8D8EB0",
            "FamilyMemberName": ""
        }
    ],
    "Reason": "Jv",
    "CreatedBy": "224a14e9-33e8-4c5a-8d48-fe20d26769f6"
}



const jsonTwo =
{
    "LangID": "1",
    "ServiceId": "1253",
    "ServiceName": "Age Domicile Certificate",
    "UserID": "224a14e9-33e8-4c5a-8d48-fe20d26769f6",
    "DivisionId": "6",
    "CertificateType": "Certificate of Age and Domicile",
    "CertificateTypeCode": "AD",
    "ApplicantSalutation": "09C5B7FA-97B9-4044-9F48-BF1B0B61FB0B",
    "ApplicantNameEnglish": "MAHESH DHANAVADE",
    "ApplicantNameMarathi": "Jayesh",//required
    "ApplicantFatherSalutation": "F844A285-2EA3-402B-BBEB-29E49606380B",
    "ApplicantFatherNameEnglish": "Father name basic screen ",
    "ApplicantFatherNameMarathi": "Father name basic screen marathi",
    "ApplicantDOB": "1953-01-10",
    "ApplicantAge": "71",
    "ApplicantMobileNo": "9999999999",
    "ApplicantGender": "F",
    "ApplicantEmailID": "jayeshnandurkar3@gmail.com",
    "ApplicantOccupation": "899BA63A-842C-4750-AA7B-907DB4554B7B",
    "ApplicantNationality": "INDIAN",
    "ResidingAtPresentAddressSince": "2023",
    "ApplicantAddress": "Basic screen applicant address ",
    "ApplicantBuilding": "Building basic screen ",
    "ApplicantSection": "Basic screen section ",
    "ApplicantStreet": "Basic screen applicant address ",
    "ApplicantLandmark": "Basic screen landmark ",
    "ApplicantStateCode": "27",
    "ApplicantDistrictCode": "506",
    "ApplicantSubDistrictCode": "4040",
    "ApplicantVillageCode": "537082",
    "ApplicantPinCode": "996633",
    "BeneficiaryResidingCurrentAddress": "2023",
    "ApplicantResidingMaharashtra": "24",
    "ApplicantRelationWithBeneficiary": "A2DB24FD-3560-4138-9F34-DE7647A42EAE",
    "BeneficiarySalutation": "09C5B7FA-97B9-4044-9F48-BF1B0B61FB0B",
    "BeneficiaryName": "Beneficiary Full name ",
    "BeneficiaryDOB": "2006-05-22",
    "BeneficiaryMobile": "9966336699",
    "PresentAddressSameAsAbove": "नाही",
    "PresentAddress": "Present address ",
    "PresentBuilding": "Building ",
    "PresentSection": "Section ",
    "PresentStreet": "Street ",
    "PresentLandmark": "Landmark ",
    "PresentDistrictCode": "530",
    "PresentSubDistrictCode": "4284",
    "PresentVillageCode": "567189",
    "PresentPinCode": "336699",
    "BirthAddressSameAsAbove": "नाही",
    "BirthAddress": "Birth address ",
    "BirthBuilding": "",
    "BirthSection": "",
    "BirthStreet": "",
    "BirthStateCode": "27",
    "BirthDistrictCode": "530",
    "BirthSubDistrictCode": "4292",
    "BirthVillageCode": "567916",
    "BirthPinCode": "996633",
    "ListEducationDetailsofBeneficiaryModel": [
        {
            "EducationDetailsofBeneficiary": "2BB4D79C-ECBE-4B3C-BFD1-4AC24764AA7E",
            "University": "",
            "AdmissionYear": "",
            "CompletionYear": "",
            "InstituteDetails": ""
        }
    ],
    "IsBeneficiaryaMarriedWoman": "24D0812D-9882-4A3E-80E8-E2B3971BA308",
    "MaidenName": "",
    "MarriageDate": "2011-05-22",
    "AddressBeforeMarriageSameasSbove": "Address after married women ",
    "BeforeMarriageAddress": "Address for married women ",
    "BeforeMarriageBuilding": "",
    "BeforeMarriageSection": "",
    "BeforeMarriageStreet": "",
    "BeforeMarriageLandmark": "",
    "BeforeMarriageDistrictCode": "530",
    "BeforeMarriageSubDistrictCode": "4293",
    "BeforeMarriageVillageCode": "567991",
    "BeforeMarriagePinCode": "996633",
    "PlacewhereMarriageWasRegistered": "",
    "PostMarriageNameAlongWithHusbandName": "",
    "ResidingPeriodBeforMarriageAndNoofYear": "2000-05-22",
    "PlaceofBirthofHusband": "",
    "DateofBirthofHusband": "1992-05-22",
    "OccupationofHusband": "23DACB05-EA28-45F1-94DF-16CA2CA6894A",
    "HusbandName": "",
    "AddressAfterMarriageSameasAbove": "नाही",
    "AfterMarriageAddress": "",
    "AfterMarriageBuilding": "",
    "AfterMarriageSection": "",
    "AfterMarriageStreet": "",
    "AfterMarriageLandmark": "",
    "AfterMarriageDistrictCode": "530",
    "AfterMarriageSubDistrictCode": "4290",
    "AfterMarriageVillageCode": "",
    "AfterMarriagePinCode": "868833",
    "HasBeneficiaryMigratedFromDifferentState": "E5B855ED-DE8A-497A-B055-98666BC365CA",
    "YearsOfResidenceInMaharashtra": "1977",
    "FamilyNativePlaceBeforeMigrationToMaharashtra": "Native Place ",//required
    "ReasonforMigration": "Reason for migration",//required
    "ListMigrationDetailsofBeneficiaryModel": [
        {
            "MigrationPlace": "Migration place \n From Year",
            "FromYear": "",
            "ToYear": ""
        }
    ],
    "DetailsOfMovablePropertyBelongToApplicantFatherhusbandInMaharashtra": "नाही",
    "PropertyAddress": "",
    "PropertyBuilding": "",
    "PropertySection": "",
    "PropertyStreet": "",
    "PropertyLandmark": "",
    "PropertyDistrictCode": "",
    "PropertySubDistrictCode": "",
    "PropertyVillageCode": "",
    "PropertyPinCode": "",
    "PropertyHolderRelationwithBeneficiary": "aa6f3900-f4f0-43df-92ba-2433093a2f42",
    "PropertyDetail": "",
    "Beneficiaryfatherhusbandplaceofresidence": "",
    "Atthetimeofbirthofthebeneficiaryplaceofresidenceoffather": "",
    "IfBeneficiaryfatherhusbandisstayingoutsideMaharashtrathenplaceofresidence": "",
    "Placeofemploymentenrolmentforschemeifany": "",
    "WhetherApplicantIsBeneficiaryOfGovernmentSchemeinOtherDistrict": "हो",
    "PolicyDistrictCode": "508",
    "PolicySubDistrictCode": "4054",
    "PolicyVillageCode": "aa6f3",
    "PolicyPinCode": "",
    "ListApplicantFamilyResidantDetailsModel": [
        {
            "RelationWithBeneficiary": "CFD7FC5B-0108-4660-8994-593D2D8D8EB0",
            "FamilyMemberName": ""
        }
    ],
    "Reason": "Jv",
    "CreatedBy": "224a14e9-33e8-4c5a-8d48-fe20d26769f6"
}



const jsonOneKeys = Object.keys(jsonOne)
const jsonTwoKeys = Object.keys(jsonTwo)
// console.log(jsonOneKeys)

// const missingKeys = 